# -*- coding: utf-8 -*-
"""homework_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmZRDOJD6b4Ep4tlgo87Rt5zv6VtE3GK
"""

import pandas as pd

# Пути к загруженным файлам
train_path = 'train_data.csv'
test_path = 'test_data.csv'

# Загрузка данных
train_data = pd.read_csv(train_path)
test_data = pd.read_csv(test_path)

# Просмотр первых строк тренировочного и тестового датасетов
# train_data.head(), test_data.head()

from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# Подготовка данных
X_train = train_data.drop(columns = ['Unnamed: 0', 'PassengerId', 'Survived'])
y_train = train_data['Survived']

# Создание и обучение модели дерева решений
clf = DecisionTreeClassifier(max_depth = 3, random_state = 21)
clf.fit(X_train, y_train)

plt.figure(figsize=(20, 10))
plot_tree(clf,
          feature_names = X_train.columns,
          class_names=['Не выжил', 'Выжил'],
          filled=True)
plt.title('Визуализация дерева решений')
plt.show()